version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:16.15.1
  working_directory: ~/repo

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  terraform: circleci/terraform@3.1.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Display pwd
          command: pwd
      - run:
          name: List assets
          command: ls -l
      - run:
          name: Install Dependencies
          command: cd src && npm install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - src
            - deploy
            - Dockerfile
  build-and-push-docker-image:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Display pwd
          command: pwd
      - run:
          name: List assets
          command: ls -l
      - aws-ecr/build-and-push-image:
          checkout: false
          repo: test
          registry-id: AWS_ACCOUNT_ID
          # workspace-root: /home/circleci/repo
      

workflows:
  test-tf:
    jobs:
      - build
      - build-and-push-docker-image:
          context: AWS
          requires:
            - build
      - terraform/apply:
          context: AWS
          attach-workspace: true
          path: ./deploy
          var_file: ./test.auto.tfvars
          requires:
            - build

