version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  terraform: circleci/terraform@3.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Display pwd
          command: pwd
      - run:
          name: List assets
          command: ls -l
      - run:
          name: Install Dependencies
          command: cd src && npm install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - src

workflows:
  test-tf:
    jobs:
      - build
#       - terraform/apply:
#           checkout: true
#           path: ./deploy
      - aws-ecr/build-and-push-image:
          context: AWS
          repo: test
          registry-id: AWS_ACCOUNT_ID
          workspace-root: ~/repo
